Update templates to match helm best practices
xoe-labs/postgres-operator pull request #1
Opened 2018-05-21 18:50 UTC by TomNeyland

Some tweaks for your pr [#228](https://github.com/CrunchyData/postgres-operator/pull/228) based on the tips in the following links, and on the default service scaffolding helm provides.
https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices
https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/templates.md\#names-of-defined-templates
https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/rbac.md\#using-rbac-resources

2018-05-21 19:40 UTC, blaggacao commented
Thanks very greateful for this hands-on teaching! :smile:

2018-05-21 19:49 UTC, blaggacao commented on chart/postgres-operator/templates/deployment.yaml
>          name: postgres-operator
Did this slip you view? Or is this supposed to be hard-coded?

2018-05-21 19:51 UTC, blaggacao commented on chart/postgres-operator/templates/service.yaml
> +      name: apiserver
Also ok to leave in this simple notation?

2018-05-21 19:52 UTC, blaggacao requested changes
The other comments are rather questions, but would you mind to add defaults in the `values.yaml`?

2018-05-21 19:52 UTC, blaggacao commented on chart/postgres-operator/templates/service.yaml
> +    - port: {{ .Values.service.port }}
We should probably provide defaults in the `values.yaml`...

2018-05-21 21:17 UTC, TomNeyland commented on chart/postgres-operator/templates/service.yaml
> +    - port: {{ .Values.service.port }}
@blaggacao good catch, updated the commit to include the new values.

2018-05-21 21:18 UTC, TomNeyland commented on chart/postgres-operator/templates/service.yaml
> +      name: apiserver
I am not quite sure what you are asking, could you rephrase the question?

2018-05-21 21:35 UTC, TomNeyland commented
Also, these tweaks don't necessarily represent an exhaustive implementation of the suggestions in [chart best practices](https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices), just a few things that caught my eye.

2018-05-21 22:59 UTC, blaggacao commented on chart/postgres-operator/templates/service.yaml
> +      name: apiserver
Sry for not being clear here:
Shouldn't `name: apiserver` rather be `name: {{ template "postgres-operator.fullname" . }}-apiserver`?

2018-05-21 22:59 UTC, blaggacao commented on chart/postgres-operator/templates/deployment.yaml
>          name: postgres-operator
Shouldn't `name: postgres-operator` rather be `name: {{ template "postgres-operator.fullname" . }} ?

2018-05-22 13:09 UTC, blaggacao approved these changes

2018-05-22 13:10 UTC, merged